language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - set -e
  - cargo clean
  - cargo build
  - cargo test
  - cargo doc --no-deps
  - cargo package
  # - cargo publish
  - set +e

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    set -e
    cargo install cargo-tarpaulin &&
    cargo tarpaulin --no-count --out Xml &&
    bash <(curl -s https://codecov.io/bash)
    set +e
  fi
